# .github/workflows/deploy.yml
name: Deploy VitePress Site

on:
  push:
    branches:
      - main
  # 你可以根据需要触发工作流的其他事件

# 添加权限配置
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 指定 Node.js 版本为 18

      - name: Set up pnpm
        run: |
          npm install -g pnpm
          pnpm config set store-dir $HOME/.pnpm-store

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist # 修正为正确的构建输出目录
          publish_branch: gh-pages # 发布到的分支
